language: node_js

node_js:
  - "12"

before_script:
  - npm install -g yarn

script:
  - yarn install --ignore-scripts
  - mocha --timeout 999999 --require ts-node/register '/tests/unit/**/*.Tests.ts'
