version: 2

jobs:
  build:
    docker:
      - image: node:latest

    working_directory: /workspace

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Execute Unit Tests
          command: mocha --require ts-node/register '/workspace/tests/unit/**/*.Tests.ts'
