version: "3.7"

services:
  build:
    image: xcompany/xbuild-mgr:devcontainer
    build: .
    volumes:


  run:
    image: xcompany/xbuild-mgr:devcontainer
    depends_on:
      - build
    volumes:
      # Map the current Source Folder
      - ..:/workspace
      - ./sources.list:/etc/xbuild/sources.list
      - ./xbuild.conf:/etc/xbuild/xbuild.conf
      # Configure Git with the current local Settings
      - ~/.gitconfig:/root/.gitconfig
      # Persists Extensions and VSCode Server
      - vscode-server:/root/.vscode-server
    cap_add:
        - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: sleep infinity

volumes:
  vscode-server:
